// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/cli.go
//
// Generated by this command:
//
//	mockgen -source internal/domain/repository/cli.go -destination internal/mocks/cli_repository.go -package mocks CLIArgsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCLIArgsRepository is a mock of CLIArgsRepository interface.
type MockCLIArgsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCLIArgsRepositoryMockRecorder
	isgomock struct{}
}

// MockCLIArgsRepositoryMockRecorder is the mock recorder for MockCLIArgsRepository.
type MockCLIArgsRepositoryMockRecorder struct {
	mock *MockCLIArgsRepository
}

// NewMockCLIArgsRepository creates a new mock instance.
func NewMockCLIArgsRepository(ctrl *gomock.Controller) *MockCLIArgsRepository {
	mock := &MockCLIArgsRepository{ctrl: ctrl}
	mock.recorder = &MockCLIArgsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCLIArgsRepository) EXPECT() *MockCLIArgsRepositoryMockRecorder {
	return m.recorder
}

// Address mocks base method.
func (m *MockCLIArgsRepository) Address() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Address")
	ret0, _ := ret[0].(string)
	return ret0
}

// Address indicates an expected call of Address.
func (mr *MockCLIArgsRepositoryMockRecorder) Address() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Address", reflect.TypeOf((*MockCLIArgsRepository)(nil).Address))
}

// ListenAddress mocks base method.
func (m *MockCLIArgsRepository) ListenAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// ListenAddress indicates an expected call of ListenAddress.
func (mr *MockCLIArgsRepositoryMockRecorder) ListenAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAddress", reflect.TypeOf((*MockCLIArgsRepository)(nil).ListenAddress))
}

// URL mocks base method.
func (m *MockCLIArgsRepository) URL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URL")
	ret0, _ := ret[0].(string)
	return ret0
}

// URL indicates an expected call of URL.
func (mr *MockCLIArgsRepositoryMockRecorder) URL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URL", reflect.TypeOf((*MockCLIArgsRepository)(nil).URL))
}

// URLPrefix mocks base method.
func (m *MockCLIArgsRepository) URLPrefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URLPrefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// URLPrefix indicates an expected call of URLPrefix.
func (mr *MockCLIArgsRepositoryMockRecorder) URLPrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLPrefix", reflect.TypeOf((*MockCLIArgsRepository)(nil).URLPrefix))
}

// Validate mocks base method.
func (m *MockCLIArgsRepository) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockCLIArgsRepositoryMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCLIArgsRepository)(nil).Validate))
}
