// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/ups.go
//
// Generated by this command:
//
//	mockgen -source internal/domain/repository/ups.go -destination internal/mocks/ups_repository.go -package mocks UPSRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/TheDarthMole/UPSWake/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUPSRepository is a mock of UPSRepository interface.
type MockUPSRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUPSRepositoryMockRecorder
	isgomock struct{}
}

// MockUPSRepositoryMockRecorder is the mock recorder for MockUPSRepository.
type MockUPSRepositoryMockRecorder struct {
	mock *MockUPSRepository
}

// NewMockUPSRepository creates a new mock instance.
func NewMockUPSRepository(ctrl *gomock.Controller) *MockUPSRepository {
	mock := &MockUPSRepository{ctrl: ctrl}
	mock.recorder = &MockUPSRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUPSRepository) EXPECT() *MockUPSRepositoryMockRecorder {
	return m.recorder
}

// GetJSON mocks base method.
func (m *MockUPSRepository) GetJSON(server *entity.NutServer) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", server)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockUPSRepositoryMockRecorder) GetJSON(server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockUPSRepository)(nil).GetJSON), server)
}
