[settings]
lockfile = true

[tools]
go = "1.26.3"
"go:go.uber.org/mock/mockgen" = "0.6.0"
golangci-lint = "2.12.2"
hadolint = "2.14.0"
hk = "1.46.0"
just = "1.51.0"
pkl = "0.31.1"
swag = "v1.16.6"
zizmor = "1.25.2"
