// Code generated by MockGen. DO NOT EDIT.
// Source: rules.go
//
// Generated by this command:
//
//	mockgen -package mocks -source rules.go -destination mocks/rules_mock.go RuleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRuleRepository is a mock of RuleRepository interface.
type MockRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockRuleRepositoryMockRecorder is the mock recorder for MockRuleRepository.
type MockRuleRepositoryMockRecorder struct {
	mock *MockRuleRepository
}

// NewMockRuleRepository creates a new mock instance.
func NewMockRuleRepository(ctrl *gomock.Controller) *MockRuleRepository {
	mock := &MockRuleRepository{ctrl: ctrl}
	mock.recorder = &MockRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleRepository) EXPECT() *MockRuleRepositoryMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockRuleRepository) Evaluate(ruleName, inputJSON string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ruleName, inputJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockRuleRepositoryMockRecorder) Evaluate(ruleName, inputJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockRuleRepository)(nil).Evaluate), ruleName, inputJSON)
}

// RuleNames mocks base method.
func (m *MockRuleRepository) RuleNames() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuleNames")
	ret0, _ := ret[0].([]string)
	return ret0
}

// RuleNames indicates an expected call of RuleNames.
func (mr *MockRuleRepositoryMockRecorder) RuleNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuleNames", reflect.TypeOf((*MockRuleRepository)(nil).RuleNames))
}
