name: Docker

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

env:
  platforms: "linux/386,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le,linux/riscv64,linux/s390x"

permissions:
  contents: read

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-build-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      id-token: write # This is required for requesting the JWT for CoSign
      contents: read  # This is required for actions/checkout
    steps:
      - name: 🛡️ Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
          #allowed-endpoints: >
            #  api.github.com:443
            #  auth.docker.io:443
            #  github.com:443
            #  objects.githubusercontent.com:443
            #  production.cloudflare.docker.com:443
            #  proxy.golang.org:443
            #  raw.githubusercontent.com:443
            #  registry-1.docker.io:443
            #  storage.googleapis.com:443
            #  sum.golang.org:443
            #  oauth2.sigstore.dev:443

      - name: 🚚 Check out the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          version: latest
      - name: 🔑 Log in to Docker
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏷️ Fetch git tags for `git describe`
        run: "git fetch --force --prune --unshallow --tags"
      - name: 📝 Run `git describe` and save its output
        run: echo 'GIT_DESCRIBE='`git describe --tags --always --long` >> $GITHUB_OUTPUT
        id: git-describe

      - name: 📝 Calculate metadata for minimal Docker images
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        id: meta
        with:
          images: ${{ github.repository }}
          tags: |
            type=edge
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
          annotations: |
            io.artifacthub.package.license=MIT
            io.artifacthub.package.readme-url=https://github.com/${{ github.repository }}/blob/main/README.md
            io.artifacthub.package.maintainers=[{"name":"DarthMole","email":"upswake@darthmole.dev"}]
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index

      - name: 🚀 Build and deploy minimal Docker images
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        id: build
        with:
          target: "minimal"
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ${{ format('GIT_DESCRIBE={0}', steps.git-describe.outputs.GIT_DESCRIBE) }}
          platforms: ${{ env.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: "mode=max"

      - name: ✍️ Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      - name: ✍️ Sign the Docker images
        if: ${{ github.event_name == 'release' }}
        run: |
          cosign sign --recursive --yes "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}@${{ steps.build.outputs.digest }}"
