name: Go

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🛡️ Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            dl.google.com:443
            github.com:443
            golangci-lint.run:443
            mise-versions.jdx.dev:443
            mise.jdx.dev:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443
            tuf-repo-cdn.sigstore.dev:443

      - name: 🚚 Check out the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 🏗️Set up Mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0

      - name: 🧹 Run HK lint
        run: hk check --all

      - name: 🧹 Run HK fix
        run: hk fix --all

      - name: 👀 Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes detected, please run 'hk fix --all' and commit the changes."
            git status --porcelain
            git diff
            exit 1
          fi
