name: Go

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 🛡️ Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - name: 🚚 Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: 🏗️Set up Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1

      - name: 🧹 Run HK lint
        run: hk check --all

      - name: 🧹 Run HK fix
        run: hk fix --all

      - name: 👀 Check for uncommitted changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Uncommitted changes detected, please run 'hk fix --all' and commit the changes."
            git diff
            exit 1
          fi
